### ISSUE TITLE
Ability to force animation to play at a specific speed

### ISSUE THREAD

**Issue by PoliceFighter761** [EgoMoose/character-animate#2]
I have a walk animation in one of my games and the automatic speed changing of the default animation script causes the animation to not play correctly. A fix I implemented for my game was to fork the animation script and force the walk and run animation to play at 1 speed. 
Maybe having a generalized API for this would be good? Having the ability to force the speed of an animation when changing it could be a good way to handle this.

**Comment by EgoMoose** [comment]
You can already do this by proxying the humanoid and using it as a director:

```Lua
local director = {}
local fakeRunning = Instance.new("BindableEvent")
director.Running = fakeRunning.Event
humanoid.Running:Connect(function(speed)
	speed = 16 -- force it to always run even if idle, etc...
	fakeRunning:Fire(speed)
end)

setmetatable(director, {
	__index = humanoid,
})

CharacterAnimate.animate(script, director :: any, humanoid)
```
